steps:
  - template: azure/install-rust.yml@templates
  - script: git clone --depth 1 https://github.com/raspberrypi/firmware.git
  - script: cargo install cross
  - script: cross build --target armv7-unknown-linux-gnueabihf --features "rpi" --release

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: thymoze
