[package]
name = "helios"
version = "0.1.0"
authors = ["David Heim <david@thymoze.me>"]
edition = "2018"

[dependencies]
structopt = "0.2"
failure = "0.1"

embedded-hal = "0.2"
linux-embedded-hal = "0.2"

smart-leds = "0.1"
apa102-spi = "0.1"
ws2812-spi = "0.1"